"""Add password methods to User model

Revision ID: 2462b9efc184
Revises: 
Create Date: 2025-04-16 10:29:28.319295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2462b9efc184'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award', schema=None) as batch_op:
        batch_op.drop_index('idx_award_user_id')

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index('idx_certificate_user_id')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_index('idx_education_user_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('tech_stack',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index('idx_project_user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_email')

    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.drop_index('idx_work_experience_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.create_index('idx_work_experience_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index('idx_project_user_id', ['user_id'], unique=False)
        batch_op.alter_column('tech_stack',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.create_index('idx_education_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index('idx_certificate_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('award', schema=None) as batch_op:
        batch_op.create_index('idx_award_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
